version: "3.8"
services:
  plc_master:
    image: conpot:latest
    container_name: plc_master
    networks:
      conpot_network:
        ipv4_address: 192.168.101.10

  plc_slave1:
    image: conpot:latest
    container_name: plc_slave1
    networks:
      conpot_network:
        ipv4_address: 192.168.101.11

  plc_slave2:
    image: conpot:latest
    container_name: plc_slave2
    networks:
      conpot_network:
        ipv4_address: 192.168.101.12

networks:
  conpot_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.101.0/24
